---
name: adb-fastboot-repo
kind: pipeline
type: docker

steps:
  - name: dockerhub
    image: plugins/docker
    settings:
      username:
          from_secret: docker_username
      password:
          from_secret: docker_password
      repo: davralin/adb-fastboot
      tags: latest
      custom_labels:
        - org.opencontainers.image.source=https://github.com/davralin/adb-fastboot
        - org.opencontainers.image.url=https://github.com/davralin/adb-fastboot

  - name: ghcr
    image: plugins/docker
    settings:
      username:
          from_secret: ghcr_username
      password:
          from_secret: ghcr_password
      repo: ghcr.io/davralin/adb-fastboot
      registry: ghcr.io
      tags: latest
      custom_labels:
        - org.opencontainers.image.source=https://github.com/davralin/adb-fastboot
        - org.opencontainers.image.url=https://github.com/davralin/adb-fastboot

  - name: trivy-scan
    image: quay.io/sighup/trivy-offline:latest
    pull: always
    commands:
      - trivy --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed --skip-update davralin/adb-fastboot

  - name: notify
    image: plugins/matrix
    when:
      status:
        - success
        - failure
    settings:
      homeserver:
        from_secret: matrix_server
      roomid:
        from_secret: matrix_room
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
